theme: jekyll-theme-slate
title: Jeff Gabriel
description: Software development thoughts and findings.
google_analytics: [UA-97044033-1]
top_post: 
- { title: 'Organizational Change and the Challenge of Porting Prior Company Practices', href: '/folklore.html' }
- { title: 'Money, Money, Money', href: '/moneymoney.html' }
- { title: 'Startup Work and Life', href: '/worklife.html'}
nav:
exclude:
- README.md
repository: jeffgabriel/jeffgabriel.github.io
encoding: utf-8
markdown: kramdown
gems:
  - jekyll-feed
author:
  twitter: jeffgabriel