theme: jekyll-theme-slate
title: Jeff's Blog
description: Software development thoughts and findings.
google_analytics: [UA-97044033-1]
top_post: 
- { title: 'Developing Software at a Startup', href: '/devprocess.html' }
nav:
exclude:
- README.md